### PR TITLE
Project: Bootstrap - Newsweek homepage Clone

### PR DESCRIPTION
**Pull request by Azeem838**
This project includes the following:

1. Responsive design using Bootstrap
2. Flex, Bootstrap Grid and Positioning used
3. Clone of newsweek.com homepage

This is a request for a review of my clone of the Newsweek homepage. Kindly find my commits and code below.

Thank you.

### CODE REVIEW

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Hi @Azeem838  👋

Your project looks good.
Nice work on this.👌

However, there are quite a few changes to be made.

- [x] Required - 1Kindly use this tool to check and fix your HTML markup with this validator https://validator.w3.org/#validate_by_upload. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png) from Pathwright)`

- [x] Required - Kindly remove the inline comments in your code. `It’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))`

- [x] Required - Also please fix the menu icon that shows on tablet and mobile screen sizes, as this doesn't exist on the original webpage. [Screenshot]👇
ice_screenshot_20200416-001901

- [x] Required - Kindly fix the way the menu bar looks on mobile screen sizes, and amend it to look like the original, as in yours the content seems quite out of place.

**THIS IS YOURS**👇
ice_screenshot_20200416-001619

**THIS IS WHAT IS EXPECTED**👇
ice_screenshot_20200416-003835

- [x] Required - In addition, kindly fix the issue that occurs in mobile screen sizes where the top navbar covers a portion of the top article. [Screenshot]👇
ice_screenshot_20200416-002100

- [x] Required - In the `Newsletter` and `Subscribe` sections just above the footer the sections look quite disarrayed with the `SIGN IN` and `SUBSCRIBE` buttons and also an image overflowing the sections.
**THIS IS YOURS**👇
ice_screenshot_20200416-002608

**THIS IS WHAT IS EXPECTED**👇
ice_screenshot_20200416-005215
ice_screenshot_20200416-005231

- [ ] OPTIONAL - Also please consider using HTML5 semantics in your code:
* Use the `<nav>` tag for navigation links.
* Use the `<main>` tag for the dominant <body> content.
* Also consider using the `<footer>`  tag for the footer of the page.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @Azeem838 
### Good job you have done :clap: but you have conflicts within your files, kindly rectify this and submit for another review.
- Happy coding!

**Review by rOluochKe — APPROVED** [review]
Hello @Azeem838 
### Good job for the work you have put in and for also making changes from previous reviews. Your project looks good and I, therefore, approve of it. Congratulations :boom: :100:
### You can now merge and submit a project completion form from your dashboard. Good luck with the next project.
- happy coding!

**Pull request merged**
